[package]
name = "countdown"
version = "0.1.0"
authors = ["qxxxb <46016483+qxxxb@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
